services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uptime_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://user:password@host:port/db
      REDIS_HOST: redis_host
      REDIS_PORT: 6379
      JWT_SECRET: your_jwt_secret
      SMTP_HOST: smtp.example.com
      SMTP_PORT: 587
      SMTP_USER: your_email@example.com
      SMTP_PASS: your_smtp_password
      SMTP_FROM: "your_email@example.com"
      PORT: 3001
      GOOGLE_CLIENT_ID: your_google_client_id
      GOOGLE_CLIENT_SECRET: your_google_client_secret
      GOOGLE_CALLBACK_URL: http://localhost:3001/api/auth/google/callback
      FRONTEND_URL: http://localhost:3000
    ports:
      - '3003:3001'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://uptime.nepsesignal.com/api
    container_name: uptime_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '3004:80'
